#Esta ordenado por orden alfabetico, para una busqueda comoda para el que este buscando
ESTACIONES = [
    "Aeropuerto",
    "Alameda",
    "Alfonso Reyes",
    "Anáhuac",
    "Apodaca Centro",
    "Arena Monterrey",
    "Aztlán",
    "Bonifacio Salinas",
    "Central",
    "Churubusco",
    "Col. Obrera",
    "Cuauhtémoc",
    "Del Golfo",
    "Edison",
    "El Milagro",
    "Eloy Cavazos",
    "Exposición",
    "Félix U. Gómez",
    "Fundadores",
    "General Anaya",
    "General I. Zaragoza",
    "Ginecología",
    "Hospital",
    "Hospital Metropolitano",
    "Isidoro Sepúlveda",
    "Julián Treviño",
    "La Talaverna",
    "La Victoria",
    "Lerdo de Tejada",
    "Lindavista",
    "Los Ángeles",
    "Macroplaza",
    "Metalúrgicos",
    "Mitras",
    "Moderna",
    "Niños Héroes",
    "Nuevo Edificio Fuerza Civil",
    "Padre Mier",
    "Parque Fundidora",
    "Paseo La Fe",
    "Penitenciaría",
    "Pino Suárez",
    "Puente del Papa",
    "Regina",
    "Ruiz Cortines",
    "San Bernabé",
    "San Nicolás",
    "San Rafael",
    "Santa Lucía",
    "Santiago Tapia",
    "Sendero",
    "Simón Bolívar",
    "Talleres",
    "Torre Rise",
    "Tren del Norte",
    "Unidad Modelo",
    "Universidad",
    "Y Griega",
]