ESTACIONES = [
    "Aeropuerto",
    "Alameda",
    "Alfonso Reyes",
    "Anáhuac",
    "Apodaca Centro",
    "Aztlán",
    "Bonifacio Salinas",
    "Central",
    "Churubusco",
    "Colonia Moderna",
    "Colonia Obrera",
    "Cuauhtémoc",
    "Del Golfo",
    "Edison",
    "El Milagro",
    "Eloy Cavazos",
    "Exposición",
    "Félix U. Gómez",
    "Fundadores",
    "General Anaya",
    "General I. Zaragoza",
    "Hospital",
    "Hospital Metropolitano",
    "Isidoro Sepúlveda",
    "Julián Treviño",
    "La Talaverna",
    "La Victoria",
    "Lerdo de Tejada",
    "Lindavista",
    "Los Ángeles",
    "Metalúrgicos",
    "Mitras",
    "Niños Héroes",
    "Nuevo Edificio Fuerza Civil",
    "Padre Mier",
    "Parque Fundidora",
    "Paseo La Fe",
    "Penitenciaría",
    "Pino Suárez",
    "Regina",
    "Ruiz Cortines",
    "San Bernabé",
    "San Nicolás",
    "San Rafael",
    "Santa Lucía",
    "Santiago Tapia",
    "Sendero",
    "Simón Bolívar",
    "Talleres",
    "Torre Rise",
    "Tren del Norte",
    "Unidad Modelo",
    "Universidad",
    "Y Griega",
]